version: "2"

run:
  timeout: 3m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - bodyclose
    - errname
    - errorlint
    - gosec
    - misspell
    - nilerr
    - prealloc
    - revive
    - unconvert
    - unparam
    - whitespace

  settings:
    errname:
      no-prefix: false
    revive:
      rules:
        - name: blank-imports
        - name: exported
        - name: unreachable-code
        - name: unused-parameter
    gosec:
      excludes:
        - G107

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
